// Generated by scripts/import-splice-dars.mjs from splice-api-token-allocation-instruction-v1-1.0.0.dar
// Do not edit manually.

import type { ChoiceDescriptor, StableInterfaceDescriptor } from './types.js'
import type { AllocationFactoryView, AllocationFactory_Allocate, AllocationFactory_PublicFetch, AllocationInstructionView, AllocationInstruction_Update, AllocationInstruction_Withdraw } from '../generated/splice-api-token-allocation-instruction-v1/Splice/Api/Token/AllocationInstructionV1.js'

export const AllocationInstructionV1 = {
  kind: 'interface' as const,
  packageName: 'splice-api-token-allocation-instruction-v1' as const,
  packageVersion: '1.0.0' as const,
  packageId: 'splice-api-token-allocation-instruction-v1-1.0.0-275064aacfe99cea72ee0c80563936129563776f67415ef9f13e4297eecbc520' as const,
  moduleName: 'Splice.Api.Token.AllocationInstructionV1' as const,
  entityName: 'AllocationInstruction' as const,
  interfaceId: '#splice-api-token-allocation-instruction-v1:Splice.Api.Token.AllocationInstructionV1:AllocationInstruction' as const,
  choices: {
    AllocationInstruction_Withdraw: { name: 'AllocationInstruction_Withdraw' as const },
    AllocationInstruction_Update: { name: 'AllocationInstruction_Update' as const },
  },
} as const satisfies StableInterfaceDescriptor<AllocationInstructionView, {
  readonly AllocationInstruction_Withdraw: ChoiceDescriptor<AllocationInstruction_Withdraw>
  readonly AllocationInstruction_Update: ChoiceDescriptor<AllocationInstruction_Update>
}>

export const AllocationFactoryV1 = {
  kind: 'interface' as const,
  packageName: 'splice-api-token-allocation-instruction-v1' as const,
  packageVersion: '1.0.0' as const,
  packageId: 'splice-api-token-allocation-instruction-v1-1.0.0-275064aacfe99cea72ee0c80563936129563776f67415ef9f13e4297eecbc520' as const,
  moduleName: 'Splice.Api.Token.AllocationInstructionV1' as const,
  entityName: 'AllocationFactory' as const,
  interfaceId: '#splice-api-token-allocation-instruction-v1:Splice.Api.Token.AllocationInstructionV1:AllocationFactory' as const,
  choices: {
    AllocationFactory_Allocate: { name: 'AllocationFactory_Allocate' as const },
    AllocationFactory_PublicFetch: { name: 'AllocationFactory_PublicFetch' as const },
  },
} as const satisfies StableInterfaceDescriptor<AllocationFactoryView, {
  readonly AllocationFactory_Allocate: ChoiceDescriptor<AllocationFactory_Allocate>
  readonly AllocationFactory_PublicFetch: ChoiceDescriptor<AllocationFactory_PublicFetch>
}>
