// Generated by scripts/import-splice-dars.mjs from splice-api-token-allocation-request-v1-1.0.0.dar
// Do not edit manually.

import type { ChoiceDescriptor, StableInterfaceDescriptor } from './types.js'
import type { AllocationRequestView, AllocationRequest_Reject, AllocationRequest_Withdraw } from '../generated/splice-api-token-allocation-request-v1/Splice/Api/Token/AllocationRequestV1.js'

export const AllocationRequestV1 = {
  kind: 'interface' as const,
  packageName: 'splice-api-token-allocation-request-v1' as const,
  packageVersion: '1.0.0' as const,
  packageId: 'splice-api-token-allocation-request-v1-1.0.0-6fe848530b2404017c4a12874c956ad7d5c8a419ee9b040f96b5c13172d2e193' as const,
  moduleName: 'Splice.Api.Token.AllocationRequestV1' as const,
  entityName: 'AllocationRequest' as const,
  interfaceId: '#splice-api-token-allocation-request-v1:Splice.Api.Token.AllocationRequestV1:AllocationRequest' as const,
  choices: {
    AllocationRequest_Reject: { name: 'AllocationRequest_Reject' as const },
    AllocationRequest_Withdraw: { name: 'AllocationRequest_Withdraw' as const },
  },
} as const satisfies StableInterfaceDescriptor<AllocationRequestView, {
  readonly AllocationRequest_Reject: ChoiceDescriptor<AllocationRequest_Reject>
  readonly AllocationRequest_Withdraw: ChoiceDescriptor<AllocationRequest_Withdraw>
}>
