// Generated by scripts/import-splice-dars.mjs from splice-api-token-allocation-v1-1.0.0.dar
// Do not edit manually.

import type { ChoiceDescriptor, StableInterfaceDescriptor } from './types.js'
import type { AllocationView, Allocation_Cancel, Allocation_ExecuteTransfer, Allocation_Withdraw } from '../generated/splice-api-token-allocation-v1/Splice/Api/Token/AllocationV1.js'

export const AllocationV1 = {
  kind: 'interface' as const,
  packageName: 'splice-api-token-allocation-v1' as const,
  packageVersion: '1.0.0' as const,
  packageId: 'splice-api-token-allocation-v1-1.0.0-93c942ae2b4c2ba674fb152fe38473c507bda4e82b4e4c5da55a552a9d8cce1d' as const,
  moduleName: 'Splice.Api.Token.AllocationV1' as const,
  entityName: 'Allocation' as const,
  interfaceId: '#splice-api-token-allocation-v1:Splice.Api.Token.AllocationV1:Allocation' as const,
  choices: {
    Allocation_ExecuteTransfer: { name: 'Allocation_ExecuteTransfer' as const },
    Allocation_Cancel: { name: 'Allocation_Cancel' as const },
    Allocation_Withdraw: { name: 'Allocation_Withdraw' as const },
  },
} as const satisfies StableInterfaceDescriptor<AllocationView, {
  readonly Allocation_ExecuteTransfer: ChoiceDescriptor<Allocation_ExecuteTransfer>
  readonly Allocation_Cancel: ChoiceDescriptor<Allocation_Cancel>
  readonly Allocation_Withdraw: ChoiceDescriptor<Allocation_Withdraw>
}>
