// Generated by scripts/import-splice-dars.mjs from splice-api-featured-app-v2-1.0.0.dar
// Do not edit manually.

import type { ChoiceDescriptor, StableInterfaceDescriptor } from './types.js'
import type { FeaturedAppActivityMarkerView, FeaturedAppRightView, FeaturedAppRight_CreateActivityMarker } from '../generated/splice-api-featured-app-v2/Splice/Api/FeaturedAppRightV2.js'

export const FeaturedAppRightV2 = {
  kind: 'interface' as const,
  packageName: 'splice-api-featured-app-v2' as const,
  packageVersion: '1.0.0' as const,
  packageId: 'splice-api-featured-app-v2-1.0.0-dd22e3e168a8c7fd0313171922dabf1f7a3b131bd9bfc9ff98e606f8c57707ea' as const,
  moduleName: 'Splice.Api.FeaturedAppRightV2' as const,
  entityName: 'FeaturedAppRight' as const,
  interfaceId: '#splice-api-featured-app-v2:Splice.Api.FeaturedAppRightV2:FeaturedAppRight' as const,
  choices: {
    FeaturedAppRight_CreateActivityMarker: { name: 'FeaturedAppRight_CreateActivityMarker' as const },
  },
} as const satisfies StableInterfaceDescriptor<FeaturedAppRightView, {
  readonly FeaturedAppRight_CreateActivityMarker: ChoiceDescriptor<FeaturedAppRight_CreateActivityMarker>
}>

export const FeaturedAppActivityMarkerV2 = {
  kind: 'interface' as const,
  packageName: 'splice-api-featured-app-v2' as const,
  packageVersion: '1.0.0' as const,
  packageId: 'splice-api-featured-app-v2-1.0.0-dd22e3e168a8c7fd0313171922dabf1f7a3b131bd9bfc9ff98e606f8c57707ea' as const,
  moduleName: 'Splice.Api.FeaturedAppRightV2' as const,
  entityName: 'FeaturedAppActivityMarker' as const,
  interfaceId: '#splice-api-featured-app-v2:Splice.Api.FeaturedAppRightV2:FeaturedAppActivityMarker' as const,
  choices: {
  },
} as const satisfies StableInterfaceDescriptor<FeaturedAppActivityMarkerView, Record<string, never>>
