// Generated by scripts/import-splice-dars.mjs from splice-api-token-holding-v1-1.0.0.dar
// Do not edit manually.

import type { StableInterfaceDescriptor } from './types.js'
import type { HoldingView } from '../generated/splice-api-token-holding-v1/Splice/Api/Token/HoldingV1.js'

export const HoldingV1 = {
  kind: 'interface' as const,
  packageName: 'splice-api-token-holding-v1' as const,
  packageVersion: '1.0.0' as const,
  packageId: 'splice-api-token-holding-v1-1.0.0-718a0f77e505a8de22f188bd4c87fe74101274e9d4cb1bfac7d09aec7158d35b' as const,
  moduleName: 'Splice.Api.Token.HoldingV1' as const,
  entityName: 'Holding' as const,
  interfaceId: '#splice-api-token-holding-v1:Splice.Api.Token.HoldingV1:Holding' as const,
  choices: {
  },
} as const satisfies StableInterfaceDescriptor<HoldingView, Record<string, never>>
