// Generated by scripts/import-splice-dars.mjs from splice-api-token-metadata-v1-1.0.0.dar
// Do not edit manually.

import type { StableInterfaceDescriptor } from './types.js'
import type { AnyContractView } from '../generated/splice-api-token-metadata-v1/Splice/Api/Token/MetadataV1.js'

export const AnyContractV1 = {
  kind: 'interface' as const,
  packageName: 'splice-api-token-metadata-v1' as const,
  packageVersion: '1.0.0' as const,
  packageId: 'splice-api-token-metadata-v1-1.0.0-4ded6b668cb3b64f7a88a30874cd41c75829f5e064b3fbbadf41ec7e8363354f' as const,
  moduleName: 'Splice.Api.Token.MetadataV1' as const,
  entityName: 'AnyContract' as const,
  interfaceId: '#splice-api-token-metadata-v1:Splice.Api.Token.MetadataV1:AnyContract' as const,
  choices: {
  },
} as const satisfies StableInterfaceDescriptor<AnyContractView, Record<string, never>>
