// Generated by scripts/import-splice-dars.mjs from splice-api-token-transfer-instruction-v1-1.0.0.dar
// Do not edit manually.

import type { ChoiceDescriptor, StableInterfaceDescriptor } from './types.js'
import type { TransferFactoryView, TransferFactory_PublicFetch, TransferFactory_Transfer, TransferInstructionView, TransferInstruction_Accept, TransferInstruction_Reject, TransferInstruction_Update, TransferInstruction_Withdraw } from '../generated/splice-api-token-transfer-instruction-v1/Splice/Api/Token/TransferInstructionV1.js'

export const TransferInstructionV1 = {
  kind: 'interface' as const,
  packageName: 'splice-api-token-transfer-instruction-v1' as const,
  packageVersion: '1.0.0' as const,
  packageId: 'splice-api-token-transfer-instruction-v1-1.0.0-55ba4deb0ad4662c4168b39859738a0e91388d252286480c7331b3f71a517281' as const,
  moduleName: 'Splice.Api.Token.TransferInstructionV1' as const,
  entityName: 'TransferInstruction' as const,
  interfaceId: '#splice-api-token-transfer-instruction-v1:Splice.Api.Token.TransferInstructionV1:TransferInstruction' as const,
  choices: {
    TransferInstruction_Accept: { name: 'TransferInstruction_Accept' as const },
    TransferInstruction_Reject: { name: 'TransferInstruction_Reject' as const },
    TransferInstruction_Withdraw: { name: 'TransferInstruction_Withdraw' as const },
    TransferInstruction_Update: { name: 'TransferInstruction_Update' as const },
  },
} as const satisfies StableInterfaceDescriptor<TransferInstructionView, {
  readonly TransferInstruction_Accept: ChoiceDescriptor<TransferInstruction_Accept>
  readonly TransferInstruction_Reject: ChoiceDescriptor<TransferInstruction_Reject>
  readonly TransferInstruction_Withdraw: ChoiceDescriptor<TransferInstruction_Withdraw>
  readonly TransferInstruction_Update: ChoiceDescriptor<TransferInstruction_Update>
}>

export const TransferFactoryV1 = {
  kind: 'interface' as const,
  packageName: 'splice-api-token-transfer-instruction-v1' as const,
  packageVersion: '1.0.0' as const,
  packageId: 'splice-api-token-transfer-instruction-v1-1.0.0-55ba4deb0ad4662c4168b39859738a0e91388d252286480c7331b3f71a517281' as const,
  moduleName: 'Splice.Api.Token.TransferInstructionV1' as const,
  entityName: 'TransferFactory' as const,
  interfaceId: '#splice-api-token-transfer-instruction-v1:Splice.Api.Token.TransferInstructionV1:TransferFactory' as const,
  choices: {
    TransferFactory_Transfer: { name: 'TransferFactory_Transfer' as const },
    TransferFactory_PublicFetch: { name: 'TransferFactory_PublicFetch' as const },
  },
} as const satisfies StableInterfaceDescriptor<TransferFactoryView, {
  readonly TransferFactory_Transfer: ChoiceDescriptor<TransferFactory_Transfer>
  readonly TransferFactory_PublicFetch: ChoiceDescriptor<TransferFactory_PublicFetch>
}>
