// Generated by scripts/import-splice-dars.mjs from splice-util-featured-app-proxies-1.2.2.dar
// Do not edit manually.

import type { ChoiceDescriptor, StableTemplateDescriptor } from './types.js'
import { WalletUserProxy as WalletUserProxyGenerated } from '../generated/splice-util-featured-app-proxies/Splice/Util/FeaturedApp/WalletUserProxy.js'
import type { WalletUserProxy as WalletUserProxyPayload, WalletUserProxy_AllocationFactory_Allocate, WalletUserProxy_Allocation_Withdraw, WalletUserProxy_BatchTransfer, WalletUserProxy_PublicFetch, WalletUserProxy_TransferFactory_Transfer, WalletUserProxy_TransferInstruction_Accept, WalletUserProxy_TransferInstruction_Reject, WalletUserProxy_TransferInstruction_Withdraw } from '../generated/splice-util-featured-app-proxies/Splice/Util/FeaturedApp/WalletUserProxy.js'

export const WalletUserProxy = {
  kind: 'template' as const,
  packageName: 'splice-util-featured-app-proxies' as const,
  packageVersion: '1.2.2' as const,
  packageId: 'splice-util-featured-app-proxies-1.2.2-2889c094cf9678b2b666221934ea56ab169a31b257450845bd53217a8cdfe44f' as const,
  moduleName: 'Splice.Util.FeaturedApp.WalletUserProxy' as const,
  entityName: 'WalletUserProxy' as const,
  templateId: WalletUserProxyGenerated.templateId,
  choices: WalletUserProxyGenerated.choices,
} as const satisfies StableTemplateDescriptor<WalletUserProxyPayload, {
  readonly WalletUserProxy_PublicFetch: ChoiceDescriptor<WalletUserProxy_PublicFetch>
  readonly WalletUserProxy_TransferFactory_Transfer: ChoiceDescriptor<WalletUserProxy_TransferFactory_Transfer>
  readonly WalletUserProxy_TransferInstruction_Accept: ChoiceDescriptor<WalletUserProxy_TransferInstruction_Accept>
  readonly WalletUserProxy_TransferInstruction_Reject: ChoiceDescriptor<WalletUserProxy_TransferInstruction_Reject>
  readonly WalletUserProxy_TransferInstruction_Withdraw: ChoiceDescriptor<WalletUserProxy_TransferInstruction_Withdraw>
  readonly WalletUserProxy_AllocationFactory_Allocate: ChoiceDescriptor<WalletUserProxy_AllocationFactory_Allocate>
  readonly WalletUserProxy_Allocation_Withdraw: ChoiceDescriptor<WalletUserProxy_Allocation_Withdraw>
  readonly WalletUserProxy_BatchTransfer: ChoiceDescriptor<WalletUserProxy_BatchTransfer>
}>
