import * as fs from 'node:fs/promises'
import * as os from 'node:os'
import * as path from 'node:path'
import JSZip from 'jszip'
import { afterEach, describe, expect, it } from 'vitest'
import { buildDemoDar } from '../test/archiveFixtures.js'
import { generateFromDar } from './generate.js'

const tempDirs: string[] = []

afterEach(async () => {
  await Promise.all(
    tempDirs.splice(0).map(async (dir) => {
      await fs.rm(dir, { recursive: true, force: true })
    }),
  )
})

async function createTempDir(prefix: string): Promise<string> {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), prefix))
  tempDirs.push(dir)
  return dir
}

describe('generateFromDar', () => {
  it('generates module files and a barrel index from a DAR', async () => {
    const tempDir = await createTempDir('cantonjs-codegen-')
    const { darBytes, packageId } = await buildDemoDar({
      packageId: 'pkg-generated',
      packageName: 'demo-package',
    })
    const darPath = path.join(tempDir, 'demo.dar')
    const outputDir = path.join(tempDir, 'generated')

    await fs.writeFile(darPath, darBytes)

    const result = await generateFromDar({
      dar: darPath,
      output: outputDir,
    })

    expect(result.packageName).toBe('demo-package')
    expect(result.packageId).toBe(packageId)
    expect(result.modules.map((module) => module.fileName)).toEqual(['Main.ts'])
    expect(result.filesWritten).toEqual([
      path.join(outputDir, 'demo-package', 'Main.ts'),
      path.join(outputDir, 'demo-package', 'index.ts'),
    ])

    const emittedModule = await fs.readFile(path.join(outputDir, 'demo-package', 'Main.ts'), 'utf8')
    const emittedIndex = await fs.readFile(path.join(outputDir, 'demo-package', 'index.ts'), 'utf8')

    expect(emittedModule).toContain('Generated by cantonjs-codegen from demo-package:Main')
    expect(emittedModule).toContain("templateId: '#demo-package:Main:Main.Asset' as const")
    expect(emittedIndex).toContain("export * from './Main.js'")
  })

  it('falls back to the package id when DAR metadata omits the package name', async () => {
    const tempDir = await createTempDir('cantonjs-codegen-')
    const { darBytes, packageId } = await buildDemoDar({
      packageId: 'pkg-fallback',
      includeMetadata: false,
    })
    const darPath = path.join(tempDir, 'fallback.dar')
    const outputDir = path.join(tempDir, 'generated')

    await fs.writeFile(darPath, darBytes)

    const result = await generateFromDar({
      dar: darPath,
      output: outputDir,
    })

    expect(result.packageName).toBe(packageId)
    expect(result.filesWritten[0]).toContain(path.join(outputDir, packageId))
  })

  it('skips empty modules without writing files', async () => {
    const tempDir = await createTempDir('cantonjs-codegen-')
    const { darBytes } = await buildDemoDar({
      packageId: 'pkg-empty',
      packageName: 'empty-package',
      emptyModule: true,
    })
    const darPath = path.join(tempDir, 'empty.dar')
    const outputDir = path.join(tempDir, 'generated')

    await fs.writeFile(darPath, darBytes)

    const result = await generateFromDar({
      dar: darPath,
      output: outputDir,
    })

    expect(result.modules).toEqual([])
    expect(result.filesWritten).toEqual([])
  })

  it('falls back to the first decoded package when the manifest main dalf is missing', async () => {
    const tempDir = await createTempDir('cantonjs-codegen-')
    const zip = new JSZip()
    const { dalfBytes, packageId } = await buildDemoDar({
      packageId: 'pkg-mismatch',
      packageName: 'fallback-main-package',
    })
    const darPath = path.join(tempDir, 'mismatch.dar')
    const outputDir = path.join(tempDir, 'generated')

    zip.file(
      'META-INF/MANIFEST.MF',
      [
        'Manifest-Version: 1.0',
        'Main-Dalf: missing/not-present.dalf',
        '',
      ].join('\n'),
    )
    zip.file(`demo/${packageId}.dalf`, dalfBytes)

    await fs.writeFile(darPath, await zip.generateAsync({ type: 'uint8array' }))

    const result = await generateFromDar({
      dar: darPath,
      output: outputDir,
    })

    expect(result.packageId).toBe(packageId)
    expect(result.packageName).toBe('fallback-main-package')
    expect(result.filesWritten).toContain(path.join(outputDir, 'fallback-main-package', 'index.ts'))
  })
})
