/**
 * Code emitter for Daml modules.
 *
 * Generates TypeScript source files from decoded Daml-LF modules.
 * Each Daml module produces one .ts file with:
 * - Type aliases for records, variants, and enums
 * - Companion const objects for templates (with templateId + choices)
 * - Choice argument type aliases
 */

import type {
  DamlModule,
  DamlDataType,
  DamlTemplate,
  DamlChoice,
  DamlField,
} from '../dar/types.js'
import { mapType } from '../mapper/typeMapper.js'

/** Generated output for a single module. */
export type EmittedModule = {
  readonly moduleName: string
  readonly fileName: string
  readonly content: string
}

/**
 * Emit a TypeScript source file for a Daml module.
 *
 * @param module - The decoded Daml module
 * @param packageName - The package name (for template IDs)
 */
export function emitModule(module: DamlModule, packageName: string): EmittedModule {
  const lines: string[] = []

  lines.push(`// Generated by cantonjs-codegen from ${packageName}:${module.name}`)
  lines.push('// Do not edit manually.')
  lines.push('')

  // Emit data types
  for (const dt of module.dataTypes) {
    const emitted = emitDataType(dt, module.name)
    if (emitted) {
      lines.push(emitted)
      lines.push('')
    }
  }

  // Emit templates
  for (const template of module.templates) {
    const emitted = emitTemplate(template, module.name, packageName)
    lines.push(emitted)
    lines.push('')
  }

  const content = lines.join('\n').trimEnd() + '\n'
  const fileName = module.name.replace(/\./g, '/') + '.ts'

  return { moduleName: module.name, fileName, content }
}

function emitDataType(dt: DamlDataType, _moduleName: string): string | null {
  const { name, typeParams, definition } = dt

  // Skip internal types (starting with lowercase or $)
  if (name.startsWith('$') || (name[0] && name[0] === name[0].toLowerCase())) {
    return null
  }

  const typeParamStr = typeParams.length > 0
    ? `<${typeParams.join(', ')}>`
    : ''

  switch (definition.kind) {
    case 'record':
      return emitRecord(name, typeParamStr, definition.fields)
    case 'variant':
      return emitVariant(name, typeParamStr, definition.constructors)
    case 'enum':
      return emitEnum(name, definition.constructors)
    default:
      return null
  }
}

function emitRecord(name: string, typeParams: string, fields: readonly DamlField[]): string {
  if (fields.length === 0) {
    return `export type ${name}${typeParams} = Record<string, never>`
  }

  const fieldLines = fields.map((f) => {
    const tsType = mapType(f.type)
    return `  readonly ${sanitizeFieldName(f.name)}: ${tsType}`
  })

  return [
    `export type ${name}${typeParams} = {`,
    ...fieldLines,
    '}',
  ].join('\n')
}

function emitVariant(name: string, typeParams: string, constructors: readonly DamlField[]): string {
  if (constructors.length === 0) {
    return `export type ${name}${typeParams} = never`
  }

  const branches = constructors.map((c) => {
    const tsType = mapType(c.type)
    if (tsType === 'Record<string, never>') {
      return `  | { readonly tag: '${c.name}' }`
    }
    return `  | { readonly tag: '${c.name}'; readonly value: ${tsType} }`
  })

  return [
    `export type ${name}${typeParams} =`,
    ...branches,
  ].join('\n')
}

function emitEnum(name: string, constructors: readonly string[]): string {
  if (constructors.length === 0) {
    return `export type ${name} = never`
  }

  const values = constructors.map((c) => `'${c}'`).join(' | ')
  return `export type ${name} = ${values}`
}

function emitTemplate(
  template: DamlTemplate,
  moduleName: string,
  packageName: string,
): string {
  const { name, choices } = template
  const templateId = `#${packageName}:${moduleName}:${name}`

  const lines: string[] = []

  // Template companion object
  const choiceEntries = choices.map((c) =>
    `    ${c.name}: { name: '${c.name}' as const },`,
  )

  lines.push(`export const ${name} = {`)
  lines.push(`  templateId: '${templateId}' as const,`)
  lines.push('  choices: {')
  lines.push(...choiceEntries)
  lines.push('  },')
  lines.push('} as const')

  // Choice argument types
  for (const choice of choices) {
    lines.push('')
    lines.push(emitChoiceArgs(name, choice))
  }

  return lines.join('\n')
}

function emitChoiceArgs(templateName: string, choice: DamlChoice): string {
  const typeName = `${templateName}_${choice.name}`

  if (choice.argType.kind === 'prim' && choice.argType.prim === 'UNIT') {
    return `export type ${typeName} = Record<string, never>`
  }

  // If the arg type is a record (con reference), it should already be emitted as a data type.
  // We just create an alias.
  const tsType = mapType(choice.argType)
  return `export type ${typeName} = ${tsType}`
}

/** Sanitize a field name to be a valid TypeScript identifier. */
function sanitizeFieldName(name: string): string {
  // If it starts with a digit or contains special chars, quote it
  if (/^[0-9]/.test(name) || /[^a-zA-Z0-9_$]/.test(name)) {
    return `'${name}'`
  }
  return name
}
