import { describe, it, expect } from 'vitest'
import { emitModule } from './emitModule.js'
import type { DamlModule, DamlType } from '../dar/types.js'

const text: DamlType = { kind: 'prim', prim: 'TEXT', args: [] }
const party: DamlType = { kind: 'prim', prim: 'PARTY', args: [] }
const unit: DamlType = { kind: 'prim', prim: 'UNIT', args: [] }

describe('emitModule', () => {
  it('emits a record type', () => {
    const module: DamlModule = {
      name: 'Main',
      dataTypes: [{
        name: 'Asset',
        typeParams: [],
        definition: {
          kind: 'record',
          fields: [
            { name: 'owner', type: party },
            { name: 'description', type: text },
            { name: 'value', type: { kind: 'prim', prim: 'NUMERIC', args: [] } },
          ],
        },
      }],
      templates: [],
    }

    const result = emitModule(module, 'my-package')
    expect(result.content).toContain('export type Asset = {')
    expect(result.content).toContain('readonly owner: string')
    expect(result.content).toContain('readonly description: string')
    expect(result.content).toContain('readonly value: string')
  })

  it('emits a variant type as discriminated union', () => {
    const module: DamlModule = {
      name: 'Main',
      dataTypes: [{
        name: 'Color',
        typeParams: [],
        definition: {
          kind: 'variant',
          constructors: [
            { name: 'Red', type: unit },
            { name: 'Custom', type: text },
          ],
        },
      }],
      templates: [],
    }

    const result = emitModule(module, 'my-package')
    expect(result.content).toContain("{ readonly tag: 'Red' }")
    expect(result.content).toContain("{ readonly tag: 'Custom'; readonly value: string }")
  })

  it('emits an enum type as string union', () => {
    const module: DamlModule = {
      name: 'Main',
      dataTypes: [{
        name: 'Status',
        typeParams: [],
        definition: {
          kind: 'enum',
          constructors: ['Active', 'Inactive', 'Archived'],
        },
      }],
      templates: [],
    }

    const result = emitModule(module, 'my-package')
    expect(result.content).toContain("export type Status = 'Active' | 'Inactive' | 'Archived'")
  })

  it('emits a template companion with templateId and choices', () => {
    const module: DamlModule = {
      name: 'Main',
      dataTypes: [],
      templates: [{
        name: 'Asset',
        choices: [
          { name: 'Transfer', consuming: true, argType: { kind: 'con', module: 'Main', name: 'TransferArgs', args: [] }, returnType: unit },
          { name: 'Archive', consuming: true, argType: unit, returnType: unit },
        ],
      }],
    }

    const result = emitModule(module, 'my-package')
    expect(result.content).toContain("templateId: '#my-package:Main:Asset' as const")
    expect(result.content).toContain("Transfer: { name: 'Transfer' as const }")
    expect(result.content).toContain("Archive: { name: 'Archive' as const }")
  })

  it('emits choice argument types', () => {
    const module: DamlModule = {
      name: 'Main',
      dataTypes: [],
      templates: [{
        name: 'Asset',
        choices: [
          { name: 'Transfer', consuming: true, argType: { kind: 'con', module: 'Main', name: 'TransferArgs', args: [] }, returnType: unit },
          { name: 'Archive', consuming: true, argType: unit, returnType: unit },
        ],
      }],
    }

    const result = emitModule(module, 'my-package')
    expect(result.content).toContain('export type Asset_Transfer = TransferArgs')
    expect(result.content).toContain('export type Asset_Archive = Record<string, never>')
  })

  it('generates correct file name from dotted module name', () => {
    const module: DamlModule = {
      name: 'Some.Deep.Module',
      dataTypes: [],
      templates: [],
    }

    const result = emitModule(module, 'pkg')
    expect(result.fileName).toBe('Some/Deep/Module.ts')
  })

  it('includes header comment', () => {
    const module: DamlModule = {
      name: 'Main',
      dataTypes: [],
      templates: [],
    }

    const result = emitModule(module, 'my-package')
    expect(result.content).toContain('Generated by cantonjs-codegen from my-package:Main')
    expect(result.content).toContain('Do not edit manually')
  })

  it('emits parameterized record types', () => {
    const module: DamlModule = {
      name: 'Main',
      dataTypes: [{
        name: 'Wrapper',
        typeParams: ['a'],
        definition: {
          kind: 'record',
          fields: [
            { name: 'value', type: { kind: 'var', name: 'a' } },
            { name: 'label', type: text },
          ],
        },
      }],
      templates: [],
    }

    const result = emitModule(module, 'pkg')
    expect(result.content).toContain('export type Wrapper<a> = {')
    expect(result.content).toContain('readonly value: a')
  })

  it('skips internal types (starting with $ or lowercase)', () => {
    const module: DamlModule = {
      name: 'Main',
      dataTypes: [
        { name: '$internal', typeParams: [], definition: { kind: 'record', fields: [] } },
        { name: 'helper', typeParams: [], definition: { kind: 'record', fields: [] } },
        { name: 'Public', typeParams: [], definition: { kind: 'record', fields: [] } },
      ],
      templates: [],
    }

    const result = emitModule(module, 'pkg')
    expect(result.content).not.toContain('$internal')
    expect(result.content).not.toContain('helper')
    expect(result.content).toContain('Public')
  })

  it('handles Optional and List types in records', () => {
    const module: DamlModule = {
      name: 'Main',
      dataTypes: [{
        name: 'Config',
        typeParams: [],
        definition: {
          kind: 'record',
          fields: [
            { name: 'tags', type: { kind: 'prim', prim: 'LIST', args: [text] } },
            { name: 'nickname', type: { kind: 'prim', prim: 'OPTIONAL', args: [text] } },
          ],
        },
      }],
      templates: [],
    }

    const result = emitModule(module, 'pkg')
    expect(result.content).toContain('readonly tags: readonly string[]')
    expect(result.content).toContain('readonly nickname: string | null')
  })

  it('emits type imports for cross-module references', () => {
    const module: DamlModule = {
      name: 'Splice.Api.Token.HoldingV1',
      dataTypes: [{
        name: 'HoldingView',
        typeParams: [],
        definition: {
          kind: 'record',
          fields: [
            {
              name: 'meta',
              type: { kind: 'con', module: 'Splice.Api.Token.MetadataV1', name: 'Metadata', args: [] },
            },
          ],
        },
      }],
      templates: [],
    }

    const result = emitModule(module, 'pkg')
    expect(result.content).toContain("import type { Metadata } from './MetadataV1.js'")
    expect(result.content).toContain('readonly meta: Metadata')
  })

  it('emits empty records, variants, and enums with explicit fallback types', () => {
    const module: DamlModule = {
      name: 'Main',
      dataTypes: [
        {
          name: 'EmptyRecord',
          typeParams: [],
          definition: { kind: 'record', fields: [] },
        },
        {
          name: 'EmptyVariant',
          typeParams: [],
          definition: { kind: 'variant', constructors: [] },
        },
        {
          name: 'EmptyEnum',
          typeParams: [],
          definition: { kind: 'enum', constructors: [] },
        },
      ],
      templates: [],
    }

    const result = emitModule(module, 'pkg')
    expect(result.content).toContain('export type EmptyRecord = Record<string, never>')
    expect(result.content).toContain('export type EmptyVariant = never')
    expect(result.content).toContain('export type EmptyEnum = never')
  })

  it('quotes invalid field names and merges duplicate cross-module imports', () => {
    const module: DamlModule = {
      name: 'Splice.Api.Token.Composite',
      dataTypes: [
        {
          name: 'CompositeView',
          typeParams: [],
          definition: {
            kind: 'record',
            fields: [
              {
                name: '1st-field',
                type: {
                  kind: 'con',
                  module: 'Splice.Api.Token.MetadataV1',
                  name: 'Metadata',
                  args: [],
                },
              },
            ],
          },
        },
      ],
      templates: [
        {
          name: 'CompositeTemplate',
          choices: [
            {
              name: 'Publish',
              consuming: true,
              argType: {
                kind: 'con',
                module: 'Splice.Api.Token.MetadataV1',
                name: 'Metadata',
                args: [],
              },
              returnType: {
                kind: 'con',
                module: 'Splice.Api.Token.MetadataV1',
                name: 'Metadata',
                args: [],
              },
            },
          ],
        },
      ],
    }

    const result = emitModule(module, 'pkg')
    expect(result.content.match(/import type \{ Metadata \} from '\.\/MetadataV1\.js'/g)).toHaveLength(1)
    expect(result.content).toContain("readonly '1st-field': Metadata")
    expect(result.content).toContain('export type CompositeTemplate_Publish = Metadata')
  })

  it('prefixes top-level sibling imports with ./', () => {
    const module: DamlModule = {
      name: 'Main',
      dataTypes: [
        {
          name: 'UsesSibling',
          typeParams: [],
          definition: {
            kind: 'record',
            fields: [
              {
                name: 'value',
                type: {
                  kind: 'con',
                  module: 'Other',
                  name: 'SiblingType',
                  args: [],
                },
              },
            ],
          },
        },
      ],
      templates: [],
    }

    const result = emitModule(module, 'pkg')
    expect(result.content).toContain("import type { SiblingType } from './Other.js'")
  })
})
